#page title
page_title                                : UTM                                       # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
github_link                               : https://github.com/utmapp/UTM
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : UTM                                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Run virtual machines on iOS

enable_smart_app_banner                   : false                                     # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself                            
email_address                             : dev@getutm.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : UTMapp
github_username                           : utmapp
discord_address                           : https://discord.gg/UV2RUgD



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Emulate any Processor
    description                           : 30+ processors supported by qemu including x86_64, ARM64, and RISC-V
    fontawesome_icon_name                 : microchip
    
  - title                                 : Run any Operating System
    description                           : Windows, Linux, and more natively and securely on iOS within an App
    fontawesome_icon_name                 : desktop

  - title                                 : Fast Emulation
    description                           : Para-virtualization with SPICE and JIT compilation with TCG
    fontawesome_icon_name                 : tachometer-alt

  - title                                 : High Compatibility
    description                           : iOS 11+ supported. Works on iPhone and iPad. No jailbreak needed
    fontawesome_icon_name                 : check

  - title                                 : Free and Open Source
    description                           : UTM and its dependencies are all free and open source
    fontawesome_icon_name                 : box-open
  
  - title                                 : Easy to Use 
    description                           : Configure and customize your VM in a native UI
    fontawesome_icon_name                 : cog
  
  - title                                 : Console Mode 
    description                           : Run headless server VMs in a native terminal
    fontawesome_icon_name                 : terminal
  
  - title                                 : Sharing 
    description                           : Shared directory, clipboard, and port forwarding
    fontawesome_icon_name                 : sync
  
  - title                                 : Multiple Inputs
    description                           : Support external keyboards, mouse, touchpads, Apple Pencil, and controllers
    fontawesome_icon_name                 : keyboard

videos                                    :
  - fsDEei0XS94
  - O19dNVTBCAs
  - q-ESpe-bq04

footer_message                            : 

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
